data:
  raw_dir: data/raw/
  processed_dir: data/processed/
  chunks_dir: data/processed/chunks/
  embeddings_dir: data/processed/embeddings/
models:
  embedding_model: sentence-transformers/all-MiniLM-L6-v2
  generator_model: gemini-2.0-flash
  gemini_api_key:   # Set via .env file or environment variable
retriever:
  top_k: 5
  faiss_index: data/processed/embeddings/index.faiss